# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=200)),
                ('prefecture', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nm', models.CharField(max_length=200)),
                ('high', models.CharField(max_length=200)),
                ('middle', models.CharField(max_length=200)),
                ('low', models.CharField(max_length=200)),
            ],
        ),
    ]
